export default [
  {
    title: "Omnifood",
    description: "Landing page for a fictional food delivery service.",
    tools: "css, javascript",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/omnifood.png",
    link: "https://omnifood-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Natours",
    description: "Landing page for a fictional nature tourism company.",
    tools: "scss (focuses on floats)",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/natours.png",
    link: "https://natours-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Trillo",
    description: "Landing page for a fictional hotel booking platform.",
    tools: "scss (focuses on flexbox)",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/trillo.png",
    link: "https://trillo-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Nexter",
    description: "Landing page for a fictional real estate agency.",
    tools: "scss (focuses on css grid)",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/nexter.png",
    link: "https://nexter-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Guess My Number",
    description: "Try to guess a randomly generated number.",
    tools: "css, javascript",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/guess_my_num.png",
    link: "https://guessmynum-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Bankist App",
    description:
      "Online banking app. Enables balance checks, money transfers, and loan requests.",
    tools: "css, javascript (focuses on arrays and user interaction)",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/bankist_app.png",
    link: "https://bankistapp-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Pig Game",
    description: "The popular dice game played with two players.",
    tools: "css, javascript",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/pig_game.png",
    link: "https://piggame-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Bankist Page",
    description: "Fictional Bank Webpage.",
    tools: "css, javascript (focuses on advanced DOM manipulation)",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/bankist_page.png",
    link: "https://bankist-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Forkify App",
    description: "Recipe application with custom recipe uploads.",
    tools:
      "scss, javascript (promises, fetch API, ES6 modules, local storage), MVC architecture",
    img: "https://raw.githubusercontent.com/Peac-h/0_learning_projects/main/forkify.png",
    link: "https://forkify-by-peach.netlify.app/",
    type: "learning projects",
  },
  {
    title: "Skilled E-Learning Landing Page",
    description: "Developed based on provided Figma design.",
    tools: "scss (focuses on implementation of an exact Figma design)",
    img: "https://raw.githubusercontent.com/Peac-h/6_Skilled-e-Learning-Landing-Page/main/Screenshot.png",
    link: "https://peac-h.github.io/6_Skilled-e-Learning-Landing-Page/",
    type: "website clones",
  },
  {
    title: "Art Gallery Website",
    description:
      "A two-page art gallery project. Developed based on provided Figma design.",
    tools: "scss (focuses on implementation of an exact Figma design)",
    img: "https://raw.githubusercontent.com/Peac-h/7_Art-Gallery-Website/main/Screenshot.png",
    link: "https://peac-h.github.io/7_Art-Gallery-Website/",
    type: "website clones",
  },
  {
    title: "Equalizer landing page",
    description: "Developed based on provided Figma design.",
    tools: "scss (focuses on implementation of an exact Figma design)",
    img: "https://raw.githubusercontent.com/Peac-h/8_Equalizer-Landing-Page/main/Screenshot.png",
    link: "https://peac-h.github.io/8_Equalizer-Landing-Page/",
    type: "website clones",
  },
  {
    title: "Typemaster Pre-Launch landing page",
    description: "Developed based on provided Figma design.",
    tools: "scss (focuses on implementation of an exact Figma design)",
    img: "https://raw.githubusercontent.com/Peac-h/9_Typemaster-Landing-Page/main/Screenshot.png",
    link: "https://peac-h.github.io/9_Typemaster-Landing-Page/",
    type: "website clones",
  },
  {
    title: "Single Page Portfolio",
    description: "Developed based on WordPress theme.",
    tools: "scss (focuses on implementation of an exact design)",
    img: "https://raw.githubusercontent.com/Peac-h/10.0_simple_portfolio_page/main/Desktop.png",
    link: "https://peac-h.github.io/10.0_simple_portfolio_page/",
    type: "website clones",
  },
  {
    title: "CSS Hovers",
    description: "Comic-inspired project based on 100DaysCSS.com challenges.",
    tools: "scss (focuses on css hover effects)",
    img: "https://raw.githubusercontent.com/Peac-h/14_css-hovers/main/Screen%20Shot%202023-03-01%20at%2010.12.45%20PM.png",
    link: "https://peac-h.github.io/14_css-hovers/",
    type: "personal projects",
  },
  {
    title: "Apple Calculator",
    description: "Designed to resemble the Apple calculator.",
    tools: "scss, javascript",
    img: "https://raw.githubusercontent.com/Peac-h/20_javascript_calculator/main/screenshot.png",
    link: "https://peac-h.github.io/20_javascript_calculator/",
    type: "personal projects",
  },
  {
    title: "Guess The Spell",
    description: "Harry Potter Spell Guessing Game.",
    tools: "scss, javascript (OOP paradigm with ES6 Classes and modules)",
    img: "https://raw.githubusercontent.com/Peac-h/21_guess_the_spell/main/Screen%20Shot%202023-03-27%20at%2010.35.12%20PM.png",
    link: "https://peac-h.github.io/21_guess_the_spell/",
    type: "personal projects",
  },
  {
    title: "Speed Typing Game",
    description: "Type famous TV show quotes with speed and precision.",
    tools:
      "scss, javascript (async functions, ES6 Modules, Promises, Fetch API)",
    img: "https://raw.githubusercontent.com/Peac-h/22_speed_typing_game/main/Screenshot2.png",
    link: "https://peac-h.github.io/22_speed_typing_game/",
    type: "personal projects",
  },
  {
    title: "Weather App",
    description: "Get up-to-date weather details for any location worldwide.",
    tools: "scss, JavaScript (ES6 modules, async functions, fetch API)",
    img: "https://raw.githubusercontent.com/Peac-h/23_weather_app/main/screenDesktop.png",
    link: "https://p-weather-app.netlify.app/",
    type: "personal projects",
  },
  {
    title: "Search The World",
    description: "Retrieves and displays country data based on user input.",
    tools: "scss, javascript (async functions, fetch API), Rest Countries API",
    img: "https://raw.githubusercontent.com/Peac-h/24_search_the_world/main/Screen%20Shot%202023-04-08%20at%207.51.10%20PM.png",
    link: "https://peac-h.github.io/24_search_the_world/",
    type: "personal projects",
  },
  {
    title: "ToDo App",
    description:
      "Lets users add, remove, edit, and mark tasks as complete. Stores data locally.",
    tools: "scss, javascript (OOP paradigm, ES6 classes, local storage)",
    img: "https://raw.githubusercontent.com/Peac-h/25_todo_app/main/Screenshot.png",
    link: "https://peac-h.github.io/25_todo_app/",
    type: "personal projects",
  },
  {
    title: "Music App",
    description:
      "Explore a collection of 10 introspective tracks with full music control functionality.",
    tools: "scss, javascript (OOP paradigm with ES6 Classes)",
    img: "https://raw.githubusercontent.com/Peac-h/26_music-player/main/Screen%20Shot%202023-04-21%20at%209.17.58%20PM.png",
    link: "https://peac-h.github.io/26_music-player/",
    type: "personal projects",
  },
  {
    title: "A Traveller's Notebook",
    description:
      "Leaflet Map Notes. Empowers users to take notes about various places on a world map.",
    tools:
      "scss, javascript (OOP paradigm, ES6 Classes, local storage), Leaflet",
    img: "https://raw.githubusercontent.com/Peac-h/27_leaflet_project/main/Screen%20Shot%202023-05-07%20at%2012.08.40%20PM.png",
    link: "https://peac-h.github.io/27_leaflet_project/",
    type: "personal projects",
  },
  {
    title: "Tic Tac Toe",
    description:
      "Unbeatable game of Tic Tac Toe, powered by a custom logic implementation.",
    tools: "scss, jQuery, OOP paradigm with ES6 Classes",
    img: "https://raw.githubusercontent.com/Peac-h/28_tic-tac-toe/main/Screen%20Shot%202023-05-07%20at%201.17.21%20PM.png",
    link: "https://peac-h.github.io/28_tic-tac-toe/",
    type: "personal projects",
  },
  {
    title: "Introducing ChatGPT",
    description: "Replica of the OpenAI (Introducing ChatGPT) landing page.",
    tools: "scss, typescript, MVC architecture",
    status: "Working on currently",
    type: "website clones",
  },
];
